/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedTenderFeedRouteImport } from "./routes/_authenticated/tender-feed";
import { Route as AuthenticatedHistoryRouteImport } from "./routes/_authenticated/history";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/dashboard";
import { Route as AuthenticatedAuditRouteImport } from "./routes/_authenticated/audit";

const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedTenderFeedRoute = AuthenticatedTenderFeedRouteImport.update({
  id: "/tender-feed",
  path: "/tender-feed",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRoute;
  "/audit": typeof AuthenticatedAuditRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/history": typeof AuthenticatedHistoryRoute;
  "/tender-feed": typeof AuthenticatedTenderFeedRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRoute;
  "/audit": typeof AuthenticatedAuditRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/history": typeof AuthenticatedHistoryRoute;
  "/tender-feed": typeof AuthenticatedTenderFeedRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/auth": typeof AuthRoute;
  "/_authenticated/audit": typeof AuthenticatedAuditRoute;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute;
  "/_authenticated/history": typeof AuthenticatedHistoryRoute;
  "/_authenticated/tender-feed": typeof AuthenticatedTenderFeedRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/audit"
    | "/dashboard"
    | "/history"
    | "/tender-feed";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/auth" | "/audit" | "/dashboard" | "/history" | "/tender-feed";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/auth"
    | "/_authenticated/audit"
    | "/_authenticated/dashboard"
    | "/_authenticated/history"
    | "/_authenticated/tender-feed";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AuthRoute: typeof AuthRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/tender-feed": {
      id: "/_authenticated/tender-feed";
      path: "/tender-feed";
      fullPath: "/tender-feed";
      preLoaderRoute: typeof AuthenticatedTenderFeedRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/history": {
      id: "/_authenticated/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/audit": {
      id: "/_authenticated/audit";
      path: "/audit";
      fullPath: "/audit";
      preLoaderRoute: typeof AuthenticatedAuditRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute;
  AuthenticatedTenderFeedRoute: typeof AuthenticatedTenderFeedRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedTenderFeedRoute: AuthenticatedTenderFeedRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
